apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: job-processor
type: Opaque
# Values are base64 encoded. Generate with: echo -n "value" | base64
# postgres     → cG9zdGdyZXM=
# guest        → Z3Vlc3Q=
# test-api-key → dGVzdC1hcGkta2V5
# jobprocessor → am9icHJvY2Vzc29y
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  postgres-db: am9icHJvY2Vzc29y
  rabbitmq-user: Z3Vlc3Q=
  rabbitmq-password: Z3Vlc3Q=
  api-key: dGVzdC1hcGkta2V5
